name: "lesson-ecs-cdk-workflow"

on:
    push:
        branches:
            - cdk

defaults:
    run:
        shell: bash
        working-directory: ./cdk

jobs:
    dockerimage:
        runs-on: ubuntu-latest
        steps:
            - name: "checkout"
              uses: actions/checkout@v4
            - uses: ./.github/actions/setup-node
            - name: "CDK Deploy Exec"
              run: |
                ls -la
                npm install
                npm run deploy
              env:
                AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_REGION: ap-northeast-1
