name: "lesson-ecs-workflow"

on:
    push:
        branches:
            - main
        paths:
            - .github/workflows/**

defaults:
    run:
        shell: bash
        working-directory: .

jobs:
    introduction:
        runs-on: ubuntu-latest
        steps:
            - name: "Hello World"
              run: |
                echo "Hello, World!"
                echo ${GIT_NAME}
                ls -la
              env:
                GIT_NAME: ${{ github.actor }}

    test:
        runs-on: ubuntu-latest
        steps:
            - name: "Vitest Exec"
              run: |
                echo "This is a Vitest exec step."
                npm run test

    build:
        runs-on: ubuntu-latest
        steps:
            - name: "Build Exec"
              run: |
                echo "This is a Build exec step."
                npm run build
                ls -la
